In [64]:
from NeuralNetwork import NeuralNetwork
import pandas as pd
from iexfinance.stocks import get_historical_data
import datetime as dt
import numpy as np

In [3]:
start = '01-01-2015'
end = dt.datetime.today()

In [51]:
overall_dataframe = pd.DataFrame(index = aal.index)

In [52]:
for stock in ['aal','dal','gld']:
    data = get_historical_data(stock, start, end, data_type ='pandas',token = 'pk_28978624c65e488392b272dbb54ae5ab',close_only = True)
    data = pd.DataFrame.from_dict(data,orient = 'index')[['close']]
    data['pct_change'] = data.pct_change()
    data = data[['pct_change']]
    data.columns = [stock]
    overall_dataframe = pd.concat([overall_dataframe,data],axis = 1)
    

In [53]:
overall_dataframe['next_change_aal'] = overall_dataframe['aal'].shift(-1)

In [54]:
def to_bool(data):
    if data >=0:
        return 1
    else:
        return -1

In [55]:
overall_dataframe['next_change_aal'] = overall_dataframe['next_change_aal'].map(to_bool)

In [57]:
overall_dataframe.dropna(inplace=True)

In [70]:
train_data = overall_dataframe.iloc[:-200]
test_data = overall_dataframe[-200:]


In [71]:
train_df_values = train_data.values

In [72]:
test_df_values = test_data.values

In [123]:
def vectorize(data):
    if data ==1:
        return [1,0]
    else:
        return [0,1]

In [141]:
def randomize():
    np.random.shuffle(train_df_values)
    train_inputs =[]
    train_answers =[]
    for x in train_df_values:
        train_inputs.append(x[:3])
        train_answers.append(vectorize(x[3]))
    return train_inputs,train_answers
test_inputs = []
test_answers = []
for x in test_df_values:
    test_inputs.append(x[:3])
    test_answers.append(vectorize(x[3]))

In [239]:
nn = NeuralNetwork(3,3,5,2,.1)

In [240]:
# data = [
#     {'inputs':[0,0],'answer':[0]},
#     {'inputs':[0,1],'answer':[1]},
#     {'inputs':[1,0],'answer':[1]},
#     {'inputs':[1,1],'answer':[1]}
# ]

In [241]:
for epoch in range(1000):
    print(epoch)
    train_inputs,train_answers = randomize()
    print(train_inputs[1])
    print(train_answers[1])
    for x in range(len(train_inputs)):
        nn.train(train_inputs[x],train_answers[x])
        

num_correct = 0
for x in range(len(test_inputs)):
    output = nn.feed_forward(test_inputs[x])
    print(output)
    output = np.argmax(output)
    answer = np.argmax(test_answers[x])
    
    if output == answer:
        num_correct+=1
print(num_correct/len(test_inputs))
    
        



0
[-0.00483338  0.00178183 -0.00184641]
[0, 1]
1
[0.00635762 0.0098401  0.00337126]
[1, 0]
2
[-0.00062383  0.00489366  0.0007764 ]
[1, 0]
3
[ 0.01229183  0.01438412 -0.00082816]
[0, 1]
4
[-0.00024845  0.00283163 -0.0061544 ]
[0, 1]
5
[0.01457976 0.000777   0.00359856]
[1, 0]
6
[0.02082886 0.02627357 0.00444711]
[0, 1]
7
[ 0.02060374  0.00932755 -0.00409939]
[0, 1]
8
[-0.00114976 -0.00121107  0.00132615]
[0, 1]
9
[0.01315486 0.01396825 0.00218398]
[0, 1]
10
[-0.00197775 -0.00829787 -0.0044277 ]
[1, 0]
11
[ 0.00072551  0.00407083 -0.01397777]
[0, 1]
12
[-0.01003344 -0.00019861  0.00066056]
[1, 0]
13
[-0.03902954 -0.01605676  0.00281988]
[0, 1]
14
[ 0.02751886  0.02557173 -0.00761486]
[1, 0]
15
[-0.00848656  0.00668665 -0.00225246]
[0, 1]
16
[0.01499375 0.00793651 0.00887178]
[0, 1]
17
[-0.03620842 -0.02099356  0.00355313]
[0, 1]
18
[-0.03228103 -0.04484398 -0.00462275]
[1, 0]
19
[ 0.00564236  0.00633947 -0.01981998]
[1, 0]
20
[ 0.00097276 -0.00214915  0.00729158]
[1, 0]
21
[-0.00863971 -

[ 0.02853698  0.01104341 -0.01049641]
[1, 0]
173
[ 0.01261077  0.00210471 -0.00597015]
[1, 0]
174
[-0.01888772 -0.01756783  0.01435951]
[1, 0]
175
[ 0.         -0.00186297 -0.00515506]
[1, 0]
176
[ 0.02610526  0.03962536 -0.00551201]
[0, 1]
177
[ 0.02174511  0.00078849 -0.00440193]
[1, 0]
178
[-0.00479945  0.00941968  0.00444939]
[1, 0]
179
[-0.02655889 -0.00347222 -0.00262553]
[0, 1]
180
[0.00681385 0.02002107 0.00017077]
[0, 1]
181
[0.04802372 0.01855431 0.00262123]
[0, 1]
182
[-0.00893313  0.0188465  -0.01037229]
[1, 0]
183
[-0.04656117 -0.02907801 -0.00786112]
[1, 0]
184
[-0.03560171 -0.03280469  0.00139653]
[0, 1]
185
[ 0.          0.00122374 -0.00496318]
[1, 0]
186
[-0.01493616 -0.02022179 -0.007181  ]
[0, 1]
187
[-0.01493616 -0.02022179 -0.007181  ]
[0, 1]
188
[ 0.01574633  0.02203084 -0.00142582]
[0, 1]
189
[ 0.00943651  0.00858291 -0.01662687]
[1, 0]
190
[-0.0051321  -0.01784718  0.00135501]
[0, 1]
191
[0.0166634  0.02152134 0.00525037]
[0, 1]
192
[ 0.03703704  0.02220349 -0.0

344
[ 0.01472064 -0.00622568 -0.00653433]
[0, 1]
345
[ 0.01122195  0.00890076 -0.01623377]
[0, 1]
346
[ 0.03182898  0.02941176 -0.00274702]
[1, 0]
347
[ 0.03257937  0.02167113 -0.00761246]
[1, 0]
348
[-0.02526778 -0.01394476 -0.00247268]
[0, 1]
349
[-0.00024845  0.00283163 -0.0061544 ]
[0, 1]
350
[-0.00089526  0.00247321 -0.00475935]
[1, 0]
351
[-0.03560763 -0.02909941  0.01741133]
[0, 1]
352
[ 0.0026824   0.00927571 -0.01080391]
[1, 0]
353
[0.00153039 0.00081867 0.00206084]
[1, 0]
354
[-0.04491363 -0.03844746  0.00253185]
[1, 0]
355
[ 0.0038674   0.0212766  -0.00288995]
[0, 1]
356
[0.01214095 0.00970033 0.00306215]
[0, 1]
357
[ 0.02561048  0.03092501 -0.01786402]
[0, 1]
358
[-0.01152738 -0.02478718  0.00066856]
[1, 0]
359
[0.00681385 0.02002107 0.00017077]
[0, 1]
360
[-0.00259373  0.01546961 -0.01488977]
[1, 0]
361
[-0.01723404 -0.01449571  0.00437863]
[0, 1]
362
[0.0178105  0.01061981 0.00209205]
[0, 1]
363
[-0.01682409 -0.01316929  0.00522406]
[1, 0]
364
[-0.00450547 -0.00770383  0.

515
[ 0.01552931  0.03366792 -0.00098619]
[1, 0]
516
[-0.01723404 -0.01449571  0.00437863]
[0, 1]
517
[-0.09122902 -0.03460744  0.00810995]
[1, 0]
518
[-0.01846533 -0.003465   -0.00692821]
[0, 1]
519
[-0.020158   -0.01899748  0.01890121]
[0, 1]
520
[-0.00114416 -0.00953678 -0.00211483]
[1, 0]
521
[ 4.67289720e-03  8.27280065e-03 -8.61697544e-05]
[0, 1]
522
[ 0.02711137  0.0179179  -0.00363699]
[1, 0]
523
[-0.02672606 -0.04202935  0.01523247]
[1, 0]
524
[ 0.0026824   0.00927571 -0.01080391]
[1, 0]
525
[0.04781391 0.03378515 0.0035897 ]
[0, 1]
526
[-0.00091912  0.00435081 -0.01734577]
[0, 1]
527
[ 0.00490196 -0.01244902 -0.01292783]
[1, 0]
528
[-0.01198541  0.00199167 -0.00147942]
[0, 1]
529
[-0.00594141 -0.00299581 -0.00770997]
[0, 1]
530
[-0.01706384 -0.01970614  0.00083008]
[0, 1]
531
[-0.00140885  0.02175687  0.002079  ]
[0, 1]
532
[ 0.01382269  0.00696409 -0.00720691]
[0, 1]
533
[-0.01502347 -0.01246508  0.00243616]
[1, 0]
534
[-0.00040766  0.01785714  0.00484923]
[1, 0]
535
[-0.049

686
[-0.04078185 -0.02904368  0.00453092]
[1, 0]
687
[0.00953062 0.01585799 0.00070163]
[1, 0]
688
[-0.00181113 -0.01723277  0.00268097]
[1, 0]
689
[-0.00949582  0.00135287  0.00474476]
[1, 0]
690
[-0.00047939  0.00731026  0.00487221]
[0, 1]
691
[-0.10010449 -0.05604847  0.00163949]
[0, 1]
692
[-0.01014098 -0.0063322  -0.00457022]
[1, 0]
693
[ 0.00592784 -0.00670474 -0.00196464]
[1, 0]
694
[ 0.00863132  0.01270129 -0.00312204]
[1, 0]
695
[ 0.010565    0.00684551 -0.00495532]
[1, 0]
696
[0.01115011 0.01033097 0.00337496]
[0, 1]
697
[ 0.00633045 -0.00060217 -0.01261599]
[1, 0]
698
[-0.01842546 -0.00253577 -0.00195542]
[0, 1]
699
[-0.02672606 -0.04202935  0.01523247]
[1, 0]
700
[-0.04340497 -0.01699771  0.00778792]
[1, 0]
701
[ 0.02066738  0.01624036 -0.00680272]
[0, 1]
702
[-0.04498064 -0.02154696  0.00112272]
[0, 1]
703
[-0.02024291 -0.01103337 -0.00199952]
[0, 1]
704
[-0.03329261  0.00424628 -0.00139975]
[1, 0]
705
[ 0.0125271   0.00111566 -0.0044702 ]
[0, 1]
706
[-0.0066529   0.001475

856
[-0.00377145  0.00702087  0.00318627]
[0, 1]
857
[ 0.00125707 -0.00370113 -0.00715702]
[0, 1]
858
[-0.01306552 -0.00756841 -0.0032688 ]
[1, 0]
859
[-0.00957592 -0.01255445  0.01611111]
[1, 0]
860
[ 0.02853698  0.01104341 -0.01049641]
[1, 0]
861
[-0.02737786 -0.02259768 -0.00540352]
[1, 0]
862
[ 0.01801201  0.04017678 -0.01297827]
[0, 1]
863
[ 0.01410721 -0.00241322 -0.0025355 ]
[1, 0]
864
[ 0.00332147 -0.00063939  0.00056518]
[1, 0]
865
[-0.04129734 -0.03495558  0.00380435]
[1, 0]
866
[-0.0168691   0.0038831  -0.00706152]
[1, 0]
867
[-0.01774235 -0.02087    -0.00507656]
[0, 1]
868
[-0.01363791 -0.0312755   0.00825481]
[0, 1]
869
[-0.01720648 -0.01268371  0.00741901]
[0, 1]
870
[ 0.00952871  0.01203477 -0.00121655]
[0, 1]
871
[ 2.75157233e-03  9.36154278e-04 -8.43953076e-05]
[1, 0]
872
[-0.02802323 -0.03374558  0.01154837]
[1, 0]
873
[0.0243563  0.01479016 0.00178847]
[0, 1]
874
[ 0.04253802  0.05352423 -0.00016713]
[1, 0]
875
[-0.00863971 -0.01180764  0.00244991]
[0, 1]
876
[-0.015